### ISSUE TITLE
Got "ERROR Local hexo not found in /github/workspace ERROR Try running: 'npm install hexo --save" message when Deploy

### ISSUE THREAD

**Issue by DeppWang** [sma11black/hexo-action#1] opened 2020-02-16 14:47 UTC
## Error:
![image](https://user-images.githubusercontent.com/21981221/74606337-a354fc00-510a-11ea-9b73-82b85afe5943.png)

## The solution:
Add command `npm install hexo --save` to entrypoint.sh, Deploy is ok. 

![image](https://user-images.githubusercontent.com/21981221/74606279-16aa3e00-510a-11ea-8824-f5c521ba12a9.png)

![image](https://user-images.githubusercontent.com/21981221/74606394-08a8ed00-510b-11ea-80e0-914069fe9d9b.png)

I found though testing that after exectueing the command `npm install hexo-cli -g`, the `hexo` has been successfully installed.

![image](https://user-images.githubusercontent.com/21981221/74606562-6f7ad600-510c-11ea-897b-c937a104928b.png)

![image](https://user-images.githubusercontent.com/21981221/74606549-56722500-510c-11ea-8c1b-ef0b49083d7a.png)

## Two question:
1. What the difference between `hexo-cli` and `hexo`? Why happen this error?
2. The  command `npm install hexo --save` need to add entrypoint.sh?

**Comment by DeppWang** [comment] 2020-02-16 14:56
This issuse all images can display properly on your computer? by the way.

**Comment by sma11black** [comment] 2020-02-22 17:30
@DeppWang 
**1. Difference between `hexo-cli` and `hexo`**
- `hexo-cli` is a cli service for create a project. When project was created, all the things doing with `hexo` module.
- `hexo` module handle project management (generate static pages, serve for preview, etc).
- They just share the `hexo` **command** (`hexo` not means module here).

**2. A potential cause of this error**
Check out line 20 in your error screenshot, there is an info "removed 50 packages". Most likely the `hexo` module was **removed** by other process. So in your solution, you try to reinstalled a latest version of `hexo` by `npm install hexo --save` seems just working. This seems like an exception in early version of `npm`. Please refer to issue #https://github.com/npm/npm/issues/17379#issue-237805333. This is fixed as of `npm@5.7.1`.

Because `hexo-action` is built from `node:13-alpine` docker image, the cause of `npm` version can be excluded. In a new virtual machine, this error can't be reproduced. So I can just speculate that this problem may be related to the early generated **package-lock.json** file.

The `hexo-action` install dependencies by specified **package-lock.json** file, which may install and cache a same `node module` version with your local project. If your project create early, the `hexo` module will be locked at an early version. Referring line 19 in your error screenshot, the `hexo-deployer-git@0.3.1` version was installed. Without specifing in `package-lock.json` file, it should install a `@2.1.0` version for now.

If possible, you can try this **solution** to make this action work without duplicate module installation, STEP following:

**step 1**: Update your local Node.js vertion, recommends 10.0 or higher.
**step 2**: Check your `package.json` file. Remove `hexo-deployer-git` dependency if it is exist.
**step 3**: Delete your `package-lock.json` (or you need backup first). Then regenerate it by command `npm install` in your project directory.
**step 4(Optional)**: Update your `hexo` to the latest version.

**3. Where `npm install hexo --save` to add**
If you want add this installation command, you need to add this into **entrypoint.sh**. Because docker image is built before "Checkout" step. If in dockerfile, `hexo` module **won't** be installed as your blog project `node module`.

*By the way*
If you would like to use your own branch of `hexo-action`, I **recommend** that you manually add the `hexo-deployer-git` and other third party dependencies into `package.json` file and regenerate `package-lock.json` locally. Then you can remove them from `entrypoint.sh` file and **cache** these dependencies before "Deploy" step.

**Comment by DeppWang** [comment] 2020-02-23 15:00
Thanks for your reply, detailed and professional. I though **4 steps** solved this issue. As your say, The main problem of this issue is the `package-lock.json`. Thranks again!!!

**Closed** 2020-02-23 15:00 UTC
